set terminal gif animate delay 2 size 500,500
set output 'double_pendulum.gif'
set xrange [-2.2:2.2]
set yrange [-2.2:2.2]
unset key
set size square
plot 'double_pendulum_frames/f1.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f2.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f3.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f4.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f5.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f6.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f7.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f8.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f9.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f10.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f11.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f12.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f13.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f14.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f15.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f16.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f17.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f18.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f19.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f20.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f21.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f22.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f23.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f24.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f25.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f26.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f27.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f28.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f29.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f30.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f31.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f32.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f33.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f34.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f35.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f36.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f37.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f38.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f39.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f40.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f41.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f42.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f43.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f44.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f45.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f46.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f47.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f48.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f49.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f50.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f51.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f52.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f53.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f54.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f55.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f56.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f57.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f58.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f59.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f60.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f61.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f62.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f63.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f64.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f65.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f66.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f67.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f68.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f69.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f70.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f71.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f72.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f73.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f74.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f75.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f76.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f77.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f78.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f79.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f80.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f81.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f82.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f83.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f84.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f85.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f86.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f87.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f88.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f89.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f90.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f91.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f92.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f93.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f94.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f95.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f96.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f97.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f98.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f99.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f100.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f101.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f102.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f103.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f104.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f105.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f106.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f107.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f108.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f109.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f110.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f111.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f112.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f113.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f114.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f115.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f116.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f117.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f118.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f119.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f120.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f121.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f122.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f123.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f124.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f125.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f126.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f127.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f128.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f129.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f130.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f131.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f132.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f133.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f134.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f135.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f136.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f137.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f138.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f139.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f140.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f141.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f142.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f143.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f144.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f145.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f146.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f147.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f148.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f149.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f150.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f151.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f152.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f153.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f154.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f155.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f156.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f157.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f158.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f159.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f160.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f161.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f162.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f163.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f164.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f165.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f166.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f167.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f168.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f169.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f170.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f171.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f172.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f173.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f174.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f175.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f176.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f177.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f178.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f179.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f180.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f181.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f182.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f183.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f184.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f185.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f186.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f187.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f188.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f189.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f190.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f191.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f192.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f193.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f194.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f195.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f196.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f197.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f198.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f199.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f200.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f201.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f202.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f203.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f204.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f205.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f206.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f207.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f208.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f209.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f210.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f211.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f212.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f213.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f214.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f215.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f216.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f217.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f218.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f219.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f220.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f221.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f222.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f223.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f224.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f225.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f226.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f227.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f228.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f229.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f230.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f231.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f232.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f233.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f234.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f235.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f236.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f237.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f238.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f239.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f240.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f241.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f242.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f243.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f244.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f245.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f246.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f247.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f248.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f249.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f250.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f251.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f252.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f253.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f254.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f255.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f256.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f257.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f258.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f259.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f260.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f261.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f262.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f263.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f264.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f265.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f266.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f267.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f268.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f269.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f270.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f271.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f272.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f273.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f274.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f275.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f276.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f277.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f278.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f279.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f280.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f281.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f282.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f283.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f284.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f285.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f286.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f287.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f288.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f289.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f290.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f291.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f292.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f293.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f294.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f295.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f296.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f297.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f298.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f299.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f300.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f301.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f302.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f303.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f304.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f305.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f306.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f307.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f308.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f309.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f310.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f311.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f312.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f313.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f314.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f315.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f316.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f317.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f318.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f319.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f320.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f321.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f322.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f323.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f324.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f325.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f326.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f327.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f328.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f329.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f330.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f331.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f332.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f333.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f334.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f335.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f336.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f337.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f338.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f339.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f340.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f341.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f342.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f343.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f344.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f345.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f346.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f347.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f348.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f349.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f350.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f351.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f352.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f353.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f354.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f355.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f356.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f357.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f358.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f359.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f360.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f361.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f362.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f363.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f364.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f365.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f366.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f367.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f368.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f369.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f370.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f371.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f372.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f373.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f374.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f375.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f376.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f377.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f378.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f379.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f380.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f381.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f382.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f383.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f384.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f385.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f386.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f387.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f388.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f389.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f390.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f391.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f392.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f393.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f394.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f395.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f396.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f397.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f398.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f399.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f400.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f401.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f402.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f403.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f404.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f405.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f406.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f407.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f408.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f409.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f410.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f411.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f412.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f413.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f414.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f415.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f416.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f417.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f418.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f419.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f420.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f421.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f422.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f423.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f424.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f425.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f426.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f427.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f428.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f429.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f430.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f431.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f432.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f433.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f434.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f435.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f436.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f437.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f438.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f439.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f440.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f441.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f442.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f443.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f444.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f445.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f446.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f447.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f448.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f449.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f450.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f451.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f452.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f453.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f454.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f455.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f456.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f457.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f458.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f459.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f460.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f461.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f462.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f463.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f464.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f465.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f466.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f467.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f468.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f469.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f470.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f471.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f472.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f473.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f474.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f475.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f476.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f477.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f478.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f479.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f480.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f481.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f482.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f483.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f484.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f485.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f486.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f487.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f488.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f489.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f490.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f491.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f492.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f493.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f494.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f495.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f496.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f497.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f498.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f499.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f500.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f501.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f502.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f503.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f504.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f505.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f506.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f507.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f508.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f509.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f510.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f511.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f512.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f513.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f514.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f515.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f516.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f517.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f518.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f519.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f520.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f521.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f522.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f523.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f524.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f525.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f526.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f527.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f528.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f529.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f530.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f531.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f532.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f533.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f534.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f535.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f536.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f537.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f538.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f539.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f540.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f541.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f542.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f543.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f544.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f545.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f546.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f547.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f548.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f549.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f550.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f551.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f552.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f553.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f554.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f555.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f556.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f557.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f558.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f559.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f560.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f561.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f562.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f563.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f564.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f565.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f566.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f567.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f568.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f569.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f570.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f571.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f572.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f573.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f574.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f575.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f576.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f577.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f578.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f579.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f580.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f581.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f582.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f583.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f584.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f585.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f586.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f587.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f588.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f589.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f590.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f591.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f592.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f593.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f594.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f595.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f596.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f597.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f598.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f599.dat' with linespoints lw 2 pt 7 ps 2
plot 'double_pendulum_frames/f600.dat' with linespoints lw 2 pt 7 ps 2
